import type { Metadata } from "next";
import localFont from "next/font/local";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
import Footer from "@/components/shared/Footer/Footer";

const instrumentSans = Instrument_Sans({
  variable: "--instrumentSans",
  subsets: ["latin"],
  weight: ["400", "600", "600", "700"],
});

const CareFreeSemiBold = localFont({
  src: "../../public/fonts/CareFreeSemiBold.woff",
  variable: "--CareFreeSemiBold",
  display: "swap",
});

const CareFreeSemiBoldItalic = localFont({
  src: "../../public/fonts/CareFreeSemiBoldItalic.woff",
  variable: "--CareFreeSemiBoldItalic",
  display: "swap",
});

const Magilio = localFont({
  src: "../../public/fonts/Magilio.ttf",
  variable: "--Magilio",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${CareFreeSemiBold.variable} ${instrumentSans.variable} ${CareFreeSemiBoldItalic.variable} ${Magilio.variable}`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
