import type { Metadata } from "next";
import localFont from "next/font/local";
import { Instrument_Sans, Inter_Tight } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
import Footer from "@/components/shared/Footer/Footer";
import { auth } from "../../auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

const instrumentSans = Instrument_Sans({
  variable: "--instrumentSans",
  subsets: ["latin"],
  weight: ["400", "600", "600", "700"],
});

const interTight = Inter_Tight({
  variable: "--interTight",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const CareFreeSemiBold = localFont({
  src: "../../public/fonts/CareFreeSemiBold.woff",
  variable: "--CareFreeSemiBold",
  display: "swap",
});

const CareFreeSemiBoldItalic = localFont({
  src: "../../public/fonts/CareFreeSemiBoldItalic.woff",
  variable: "--CareFreeSemiBoldItalic",
  display: "swap",
});

const Magilio = localFont({
  src: "../../public/fonts/Magilio.ttf",
  variable: "--Magilio",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body
          className={`${CareFreeSemiBold.variable} ${instrumentSans.variable} ${CareFreeSemiBoldItalic.variable} ${Magilio.variable} ${interTight.variable} `}
        >
          <Nav />
          <Toaster
            position='top-right'
            toastOptions={{
              className: "toastFont",
            }}
          />
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
