import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const CareFreeSemiBold = localFont({
  src: "../../public/fonts/CareFreeSemiBold.woff",
  variable: "--CareFreeSemiBold",
  display: "swap",
});

const CareFreeSemiBoldItalic = localFont({
  src: "../../public/fonts/CareFreeSemiBoldItalic.woff",
  variable: "--CareFreeSemiBoldItalic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${CareFreeSemiBold.variable} ${poppins.variable} ${CareFreeSemiBoldItalic.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
